version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-app/aws-node
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root

  DownloadBundle:
    - location: scripts/download_bundle.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  Install:
    - location: scripts/install.sh
      timeout: 900
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 900
      runas: root
      
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 900
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 900
      runas: root